"""add tg-chat-id to user model

Revision ID: eb30861552a9
Revises: 20260414_0001
Create Date: 2026-04-24 19:24:58.666262
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'eb30861552a9'
down_revision = '20260414_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_records_record_date'), table_name='emotion_records')
    op.drop_index(op.f('ix_emotion_records_user_id'), table_name='emotion_records')
    op.alter_column('recommendations', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_recommendations_category'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_is_active'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_trigger_type'), table_name='recommendations')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_user_coping_methods_user_id'), table_name='user_coping_methods')
    op.drop_index(op.f('ix_user_hobbies_user_id'), table_name='user_hobbies')
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.create_index(op.f('ix_user_hobbies_user_id'), 'user_hobbies', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_coping_methods_user_id'), 'user_coping_methods', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_trigger_type'), 'recommendations', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_recommendations_is_active'), 'recommendations', ['is_active'], unique=False)
    op.create_index(op.f('ix_recommendations_category'), 'recommendations', ['category'], unique=False)
    op.alter_column('recommendations', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_emotion_records_user_id'), 'emotion_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_emotion_records_record_date'), 'emotion_records', ['record_date'], unique=False)
    # ### end Alembic commands ###
